name: Build and upload images

on:
  workflow_dispatch:
  schedule:
    # First day of every month, you know, for automatic updates etc.
    - cron: "0 0 1 * *"
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  build_and_upload:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"

      - name: Install regctl
        run: |
          set -ex

          INSTALL_DIR="$HOME/.regctl"
          OS=linux
          ARCH=amd64

          mkdir -p "$INSTALL_DIR"

          # Download and Install regctl
          curl -fsSL "https://github.com/regclient/regclient/releases/download/${VERSION}/regctl-${OS}-${ARCH}" > "${INSTALL_DIR}/regctl"
          chmod 755 "${INSTALL_DIR}/regctl"

          # Validate download
          if which cosign >/dev/null; then
            curl -fsSL https://github.com/regclient/regclient/releases/latest/download/metadata.tgz > metadata.tgz
            tar -xzf metadata.tgz regctl-${OS}-${ARCH}.pem regctl-${OS}-${ARCH}.sig
            cosign verify-blob \
              --certificate-oidc-issuer https://token.actions.githubusercontent.com \
              --certificate-identity-regexp https://github.com/regclient/regclient/.github/workflows/ \
              --certificate regctl-${OS}-${ARCH}.pem \
              --signature regctl-${OS}-${ARCH}.sig \
              "${{ inputs.install-dir }}/regctl"
            rm -rf metadata.tgz regctl-${OS}-${ARCH}.pem regctl-${OS}-${ARCH}.sig
          fi

          # Add it to environment
          echo "${INSTALL_DIR}" >> $GITHUB_PATH
        env:
          VERSION: v0.4.7

      - name: Check regctl installation
        run: regctl version

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          # For now hardcoding the image to the latest version found in a successful run of the action, it seems like
          # it is using quemu v7.0.0. The "tonistiigi/binfmt:latest" with qemu-v9.2.0 runs into this error:
          # Setting up libc-bin (2.35-0ubuntu3.9) ...
          # qemu: uncaught target signal 11 (Segmentation fault) - core dumped
          image: "tonistiigi/binfmt@sha256:66e11bea77a5ea9d6f0fe79b57cd2b189b5d15b93a2bdb925be22949232e4e55"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Setup custom builder
        run: |
          docker buildx create --use --bootstrap --name multi-builder --platform linux/arm64,linux/amd64 --driver-opt network=host

      - name: Run local Docker registry
        run: docker run -d -p 5000:5000 --name registry --network=host registry:2

      - name: Install Dibber
        run: pip install dibber

      - name: Build images
        run: dibber build-multiplatform --parallel 8

      - name: Upload images
        if: success()
        run: |
          dibber upload
